// <auto-generated />
using BrewBuddy.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BrewBuddy.API.Migrations
{
    [DbContext(typeof(BrewBuddyContext))]
    [Migration("20250530104259_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("BrewBuddy.API.Models.BrewRecipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("BatchSizeLiters")
                        .HasColumnType("REAL");

                    b.Property<int>("BoilTimeMin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MashTempC")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MashTimeMin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Yeast")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BrewRecipes");
                });

            modelBuilder.Entity("BrewBuddy.API.Models.HopAddition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AmountGrams")
                        .HasColumnType("REAL");

                    b.Property<int>("BrewRecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HopName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeMin")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BrewRecipeId");

                    b.ToTable("HopAdditions");
                });

            modelBuilder.Entity("BrewBuddy.API.Models.HopAddition", b =>
                {
                    b.HasOne("BrewBuddy.API.Models.BrewRecipe", "BrewRecipe")
                        .WithMany("HopSchedule")
                        .HasForeignKey("BrewRecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BrewRecipe");
                });

            modelBuilder.Entity("BrewBuddy.API.Models.BrewRecipe", b =>
                {
                    b.Navigation("HopSchedule");
                });
#pragma warning restore 612, 618
        }
    }
}
